### ISSUE TITLE
drag & dropping a MID file, and once again

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qsynth#5]
If I drag & drop a midi file on the GUI, it starts to play it. Sweet.
If I drag & drop a second midi file while it's playing, it keeps playing the same first one.

As an user point of view, I would expect Qsynth to switch playing the second midi file when dropped on the GUI.

**Comment by rncbc** [comment]
playback is run under libfluidsynth as its native primitive player sequencer, for that matter.

at the time it was written , more than a decade ago,there were no means (API) to tell libfluidsynth to stop or even to queue into a new MIDI file; you'll have to wait for the current to end to play the next one. same with panic command.

i'll look if things got friendlier in that respect on latest libfluidsynth standing.

byee

**Comment by trebmuh** [comment]
OK, thanks. Let me know if you need some testing then.

**Comment by rncbc** [comment]
scrap all of what i've said in my last comment: qsynth does actually load soundfont files (*.sf2) when drag-n-dropped over the GUI; same for queuing more than one MIDI file for playing.

dropped SF2 files are appended to the current engine soundfont stack, with bank offset set to zero, so that previously loaded soundfont(s) may well override the newer ones; you still have to tweak bank-offsets manually.

dropped MIDI files are queued in the internal MIDI player and only start playing **after** the current one ends: there is no facility to stop or skip currently playing MIDI files, sorry. only by restarting the engine which does resets the respective MIDI file player as well.

hth.

**Comment by trebmuh** [comment]
More than a year later is a great timing to say thanks for the explanation and to close this issue! :)
It's not really user-friendly but once you know how it works, it makes sense.
